name: CI Pipeline

on:
  push:
    branches:
      - main
      - teste-actions
  pull_request:
    branches:
      - main
      - teste-actions

jobs:
  lint-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install dependencies
        run: ./mvnw install
        working-directory: ./backend
      - name: Run lint
        run: ./mvnw checkstyle:check
        working-directory: ./backend

  test-backend:
    runs-on: ubuntu-latest
    needs: lint-backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install dependencies
        run: ./mvnw install
        working-directory: ./backend
      - name: Run tests
        run: ./mvnw test
        working-directory: ./backend

  build-backend:
    runs-on: ubuntu-latest
    needs: test-backend
    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Install dependencies
        run: ./mvnw install
        working-directory: ./backend
      - name: Build project
        run: ./mvnw package
        working-directory: ./backend

  deploy-backend:
    runs-on: ubuntu-latest
    needs: build-backend
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy Backend
        run: |
          echo "Deploying Backend..."
          # Adicione aqui o comando de deploy, por exemplo:
          # scp -r ./target/* user@server:/path/to/deploy
